apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neko-bot
resources:
  - neko-bot.yaml
  - redis.yaml
secretGenerator:
  - name: neko-bot-secret
    envs:
      - ../../env/prod.env
    options:
      disableNameSuffixHash: true