name: "Notify updated develop branch"

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST  -H "Content-Type: application/json" "${{ secrets.WEBHOOK_URL }}" -d '{"content": "<@&1304300205805539418> develop更新されたからpull忘れないでね！！！"}'
