name: Release Image

on:
  release:
    types: [created, edited]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Extract version from release tag
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Checkout source at release/${{ steps.vars.outputs.version }}
        uses: actions/checkout@v3
        with:
          ref: release/${{ steps.vars.outputs.version }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: naoido
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version }}
            ghcr.io/${{ github.repository }}:latest

      - name: Replace image tag in manifests
        run: |
          VERSION=${{ steps.vars.outputs.version }}
          sed -i "s|ghcr.io/naoido/neko-bot:[^\" ]*|ghcr.io/naoido/neko-bot:$VERSION|g" k8s-manifests/neko-bot/neko-bot.yaml

      - name: Commit and push updated manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s-manifests/neko-bot/neko-bot.yaml
          git commit -m "chore: update image tag to ${{ steps.vars.outputs.version }}" || echo "No changes"
          git push