name: Release Image

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Extract version from branch
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/release/}
          echo "version=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: naoido
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version }}
            ghcr.io/${{ github.repository }}:latest

      - name: Replace image tag in manifests
        run: |
          VERSION=${{ steps.vars.outputs.version }}
          sed -i "s|ghcr.io/naoido/neko-bot:latest|ghcr.io/naoido/neko-bot:$VERSION|g" k8s-manifests/neko-bot.yaml

      - name: Commit and push updated manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s-manifests/neko-bot.yaml
          git commit -m "chore: update image tag to ${{ steps.vars.outputs.version }}"
          git push